### ISSUE TITLE
Typescript build error

### ISSUE THREAD

**Issue by tamascsaba** [angular-class/angular2-universal-starter#2]
```
ERROR in ./src/bootstrap.ts
(6,1): error TS2346: Supplied parameters do not match any signature of call target.
```

when I add to webpack.config.js:
```
  ts: {
    ignoreDiagnostics: [2346]
  }
```
then compiled, but come error from angular2/src/core/dom/parse5_adapter.js (missing parse5, lodash, and css and require errors)

**Comment by gdi2290** [comment]
If you delete your node_modules and install again does it work? If not can you submit a pull request

**Comment by ICesarI** [comment]
Same here.
After typing ts-node server.ts I got:
Error: Cannot find module 'parse5/index'

**Comment by gdi2290** [comment]
ok I found the problem. can you run this command in your terminal 
`npm install -g ts-node webpack webpack-dev-server`

**Comment by ICesarI** [comment]
Thank you Patrick, it's working now.
